language: ruby

rvm:
  - 2.6.6

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rails webpacker:compile

  - bundle exec rails test test/models/paciente_test.rb
  
  - bundle exec cucumber features/psicologo.feature
  - bundle exec cucumber features/paciente.feature