language: ruby

rvm:
  - 2.7.2

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rake db:setup
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rails webpacker:compile
